[package]
name = "nix-update-flake"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
csv = "1.3.0"
directories = "5.0.1"
serde = { version = "1.0.204", features = ["derive"] }
